"""Generate a caller credentials PDF by reading supabase/seed_callers.local.sql
(the source of truth that gets run in Supabase). This keeps the PDF in sync with
the actual passwords and avoids hardcoding any secret in a committed script.

Output: GroundGame_Caller_Logins.local.pdf (gitignored).
Run:    python scripts/make_caller_logins_pdf.py
"""
import re
from fpdf import FPDF

SQL = "supabase/seed_callers.local.sql"
text = open(SQL, encoding="utf-8").read()

# Each caller block starts with a comment line:
#   -- caller: <email>  ->  <region> . <conName> (<code>)
# followed by an INSERT containing the full_name and the bcrypt'd password.
blocks = text.split("-- caller:")[1:]
callers = []
for b in blocks:
    email = b.strip().split()[0]
    m_scope = re.search(r"->\s*(.+?)\s*\((\w+)\)", b)
    m_name = re.search(r"'full_name',\s*'([^']+)'", b)
    m_pw = re.search(r"crypt\('([^']+)'", b)
    if not (m_scope and m_name and m_pw):
        continue
    scope = m_scope.group(1).replace("·", "/").replace("  ", " ").strip()
    callers.append({
        "name": m_name.group(1),
        "email": email,
        "password": m_pw.group(1),
        "constituency": scope,
        "code": m_scope.group(2),
    })

if not callers:
    raise SystemExit(f"No callers parsed from {SQL} — generate it first with build_callers_sql.mjs")

GREEN = (10, 125, 52)
INK = (20, 27, 40)
GREY = (110, 120, 135)

pdf = FPDF(orientation="P", unit="mm", format="A4")
pdf.set_auto_page_break(auto=True, margin=16)
pdf.add_page()

pdf.set_fill_color(*GREEN)
pdf.rect(0, 0, 210, 26, "F")
pdf.set_xy(14, 7)
pdf.set_text_color(255, 255, 255)
pdf.set_font("Helvetica", "B", 18)
pdf.cell(0, 6, "GroundGame - Caller Logins", ln=1)
pdf.set_xy(14, 15)
pdf.set_font("Helvetica", "", 10)
pdf.cell(0, 6, "NDC Delegate Mobilization & Call-Tracking Platform - CONFIDENTIAL", ln=1)

pdf.ln(16)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "", 9)
pdf.set_x(14)
pdf.multi_cell(182, 5,
    "Each caller signs in at the app login, chooses the Caller portal, and lands on a console "
    "limited to the single constituency assigned below. They can call delegates and log each "
    "outcome; their progress feeds the campaign dashboard. Keep this document private and change "
    "passwords after first login.")
pdf.ln(3)

# Column header
pdf.set_x(14)
pdf.set_fill_color(238, 242, 247)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "B", 8)
pdf.cell(38, 7, "  Name", fill=True)
pdf.cell(64, 7, "Email", fill=True)
pdf.cell(40, 7, "Password", fill=True)
pdf.cell(40, 7, "Constituency", fill=True, ln=1)

for c in callers:
    pdf.set_x(14)
    pdf.set_text_color(*INK)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.cell(38, 7, "  " + c["name"])
    pdf.cell(64, 7, c["email"])
    pdf.set_font("Courier", "B", 9)
    pdf.cell(40, 7, c["password"])
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GREY)
    pdf.cell(40, 7, c["constituency"], ln=1)

pdf.ln(6)
pdf.set_x(14)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "I", 8)
pdf.multi_cell(182, 4,
    "Generated by GroundGame from supabase/seed_callers.local.sql. To activate these logins, run "
    "that SQL file in the Supabase SQL editor. Store this file securely.")

out = "GroundGame_Caller_Logins.local.pdf"
pdf.output(out)
print(f"Wrote {out} ({len(callers)} callers)")
for c in callers:
    print(f"  {c['constituency']:28}  {c['email']:32}  {c['password']}")
