"""Generate a credentials PDF from scripts/accounts.local.json.
Output: GroundGame_Logins.local.pdf (gitignored). Run: python scripts/make_logins_pdf.py
"""
import json
from fpdf import FPDF

ROLE_LABEL = {
    "super_admin": "Super Admin",
    "regional_coordinator": "Regional Coordinator",
    "constituency_coordinator": "Constituency Coordinator",
    "analyst": "Analyst",
}
REGION = {
    "GAR": "Greater Accra", "ASH": "Ashanti", "NOR": "Northern", "VOL": "Volta", "CEN": "Central",
}
CON = {"GAR03": "Ablekuma North", "ASH18": "Bantama", "CEN11": "Effutu"}

accounts = json.load(open("scripts/accounts.local.json", encoding="utf-8"))

GREEN = (10, 125, 52)
INK = (20, 27, 40)
GREY = (110, 120, 135)

pdf = FPDF(orientation="P", unit="mm", format="A4")
pdf.set_auto_page_break(auto=True, margin=16)
pdf.add_page()

# Header band
pdf.set_fill_color(*GREEN)
pdf.rect(0, 0, 210, 26, "F")
pdf.set_xy(14, 7)
pdf.set_text_color(255, 255, 255)
pdf.set_font("Helvetica", "B", 18)
pdf.cell(0, 6, "GroundGame - Dashboard Logins", ln=1)
pdf.set_xy(14, 15)
pdf.set_font("Helvetica", "", 10)
pdf.cell(0, 6, "NDC Delegate Mobilization & Call-Tracking Platform - CONFIDENTIAL", ln=1)

pdf.ln(16)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "", 9)
pdf.set_x(14)
pdf.multi_cell(182, 5,
    "These are the dashboard accounts across each role level. Sign in at the app login with the "
    "email + password below. Keep this document private and change passwords after first login. "
    "Field callers do not log in - they work in the constituency Google Sheet.")
pdf.ln(2)


def scope_of(a):
    if a["role"] == "super_admin":
        return "National"
    if a["role"] == "analyst":
        return REGION.get(a.get("region"), "National (read-only)")
    if a["role"] == "regional_coordinator":
        return REGION.get(a.get("region"), "-")
    return f"{REGION.get(a.get('region'),'')} / {CON.get(a.get('constituency'), a.get('constituency',''))}"


# Group by role for readability
order = ["super_admin", "regional_coordinator", "constituency_coordinator", "analyst"]
by_role = {r: [a for a in accounts if a["role"] == r] for r in order}

for role in order:
    rows = by_role[role]
    if not rows:
        continue
    pdf.ln(3)
    pdf.set_x(14)
    pdf.set_text_color(*GREEN)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, ROLE_LABEL[role], ln=1)

    # column header
    pdf.set_x(14)
    pdf.set_fill_color(238, 242, 247)
    pdf.set_text_color(*GREY)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(40, 7, "  Name", border=0, fill=True)
    pdf.cell(62, 7, "Email", border=0, fill=True)
    pdf.cell(42, 7, "Password", border=0, fill=True)
    pdf.cell(38, 7, "Scope", border=0, fill=True, ln=1)

    for a in rows:
        pdf.set_x(14)
        pdf.set_text_color(*INK)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.cell(40, 7, "  " + a["name"])
        pdf.cell(62, 7, a["email"])
        pdf.set_font("Courier", "B", 9)
        pdf.cell(42, 7, a["password"])
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GREY)
        pdf.cell(38, 7, scope_of(a), ln=1)

pdf.ln(6)
pdf.set_x(14)
pdf.set_text_color(*GREY)
pdf.set_font("Helvetica", "I", 8)
pdf.multi_cell(182, 4,
    "Generated by GroundGame. Passwords are randomly generated. To activate these accounts, run "
    "scripts/provision_users.mjs with the Supabase service-role key. Store this file securely.")

out = "GroundGame_Logins.local.pdf"
pdf.output(out)
print(f"Wrote {out} ({len(accounts)} accounts)")
